### PR TITLE
Migrate from Drone to GitHub Action

### PR DESCRIPTION
**Pull request by jiaqiluo**
The GHA workflows are validated on [this branch](https://github.com/jiaqiluo/ingress-nginx/tree/gha-nginx-1.9.x-fix-validation) where personal DockerHub credential and Docker image repo are used:
- the workflow `CI on Push and Pull Request`  ran and passed on this PR, see the `checks` section on this page 
- the workflow `CI on Releasing Tag` passed [here](https://github.com/jiaqiluo/ingress-nginx/actions/runs/8990510147) and the image is pushed to DockerHub [here](https://hub.docker.com/repository/docker/jq20/nginx-ingress-controller/tags)

### CODE REVIEW

**Review by dereknola — APPROVED** [review]

**Review by dereknola — COMMENTED** [review]
Probably don't need these lines anymore in the dapper file

https://github.com/rancher/ingress-nginx/pull/130/files#diff-3598233dce47ce9c207a77a9f23394d45235397dd66d7dd9de909487e1bd8e8aR17-R20

```
ENV HOST_ARCH=${DAPPER_HOST_ARCH} \
    ARCH=${DAPPER_HOST_ARCH} \
    DOCKER_USER=${DOCKER_USER} \
    DOCKER_PASS=${DOCKER_PASS}
```

**Review by dereknola — COMMENTED** [review]
In the dapper file, you may want to take the opportunity to update the docker buildx version 

```
ENV DOCKER_BUILDX_URL_arm=https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-arm-v7 \
    DOCKER_BUILDX_URL_arm64=https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-arm64 \
    DOCKER_BUILDX_URL_amd64=https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64 \
    DOCKER_BUILDX_URL=DOCKER_BUILDX_URL_${ARCH}
```

**Comment by jiaqiluo** [comment]
Hi @dereknola, thank you for your suggestions, as this PR focuses on the migration,  I am going to hold those cleanup and version-bumping to another PR. We might just drop Dapper totally in the next PR :)

**Comment by dereknola** [comment]
Sounds good!

**Review by HarrisonWAffel — APPROVED** [review]
The new workflows lgtm, I assume we're deleting the old workflows since they use an action which has not been allowed (`dorny/paths-filter`)?

**Comment by jiaqiluo** [comment]
@HarrisonWAffel,  that is one of the reasons, another reason is that there is no need for us to run those chart-related and e2e tests because we pull the code at upstream's tags which has passed all those tests; it becomes a waste of GHA's (free) runtimes because we never check those results.

**Pull request merged**
